//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auth.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Auth.API.Constants.ValidationErrorCodes", typeof(ValidationErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONDITION_NOT_MET.
        /// </summary>
        public static string AsyncPredicateValidator {
            get {
                return ResourceManager.GetString("AsyncPredicateValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_BE_VALID_CREDIT_CARD.
        /// </summary>
        public static string CreditCardValidator {
            get {
                return ResourceManager.GetString("CreditCardValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL_INVALID.
        /// </summary>
        public static string EmailValidator {
            get {
                return ResourceManager.GetString("EmailValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_BE_EMPTY.
        /// </summary>
        public static string EmptyValidator {
            get {
                return ResourceManager.GetString("EmptyValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_BE_ENUM_MEMBER.
        /// </summary>
        public static string EnumValidator {
            get {
                return ResourceManager.GetString("EnumValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_BE_EQUAL.
        /// </summary>
        public static string EqualValidator {
            get {
                return ResourceManager.GetString("EqualValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_BE_EXACT_LENGTH.
        /// </summary>
        public static string ExactLengthValidator {
            get {
                return ResourceManager.GetString("ExactLengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_BE_BETWEEN_EXCLUSIVE.
        /// </summary>
        public static string ExclusiveBetweenValidator {
            get {
                return ResourceManager.GetString("ExclusiveBetweenValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_BE_GREATER_OR_EQ.
        /// </summary>
        public static string GreaterThanOrEqualValidator {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_BE_GREATER.
        /// </summary>
        public static string GreaterThanValidator {
            get {
                return ResourceManager.GetString("GreaterThanValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_BE_BETWEEN.
        /// </summary>
        public static string InclusiveBetweenValidator {
            get {
                return ResourceManager.GetString("InclusiveBetweenValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LENGTH_MUST_BE_IN_RANGE.
        /// </summary>
        public static string LengthValidator {
            get {
                return ResourceManager.GetString("LengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_BE_LESS_OR_EQ.
        /// </summary>
        public static string LessThanOrEqualValidator {
            get {
                return ResourceManager.GetString("LessThanOrEqualValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_BE_LESS.
        /// </summary>
        public static string LessThanValidator {
            get {
                return ResourceManager.GetString("LessThanValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LENGTH_MUST_BE_AT_MAX.
        /// </summary>
        public static string MaximumLengthValidator {
            get {
                return ResourceManager.GetString("MaximumLengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LENGTH_MUST_BE_AT_LEAST.
        /// </summary>
        public static string MinimumLengthValidator {
            get {
                return ResourceManager.GetString("MinimumLengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_NOT_BE_EMPTY.
        /// </summary>
        public static string NotEmptyValidator {
            get {
                return ResourceManager.GetString("NotEmptyValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_NOT_BE_EQUAL.
        /// </summary>
        public static string NotEqualValidator {
            get {
                return ResourceManager.GetString("NotEqualValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_BE_NON_NULL.
        /// </summary>
        public static string NotNullValidator {
            get {
                return ResourceManager.GetString("NotNullValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUST_BE_NULL.
        /// </summary>
        public static string NullValidator {
            get {
                return ResourceManager.GetString("NullValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONDITION_NOT_MET.
        /// </summary>
        public static string PredicateValidator {
            get {
                return ResourceManager.GetString("PredicateValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_FORMAT.
        /// </summary>
        public static string RegularExpressionValidator {
            get {
                return ResourceManager.GetString("RegularExpressionValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGNATURE_INVALID.
        /// </summary>
        public static string SignatureInvalid {
            get {
                return ResourceManager.GetString("SignatureInvalid", resourceCulture);
            }
        }
    }
}
